DROP TABLE IF EXISTS LIFE_EVENT;
DROP TABLE IF EXISTS BENIFIT;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS MEMBER_INFO;


CREATE TABLE MEMBER_INFO (USAA_ID int NOT NULL AUTO_INCREMENT, MARITAL_CD varchar(255) NOT NULL, DEPLOYED varchar(255) NOT NULL, ADDRESS varchar(255) NOT NULL,CITY varchar(255) NOT NULL,STATE varchar(255) NOT NULL,COUNTRY varchar(255) NOT NULL, PRIMARY KEY(USAA_ID));
CREATE TABLE PRODUCT(PRODUCT_ID int NOT NULL AUTO_INCREMENT,PRODUCT_NAME varchar(255) NOT NULL, PRIMARY KEY(PRODUCT_ID));
CREATE TABLE BENIFIT(BENIFIT_ID int NOT NULL AUTO_INCREMENT,BENIFIT_NAME varchar(255) NOT NULL,PRODUCT_ID int NOT NULL, PRIMARY KEY(BENIFIT_ID),FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID));
CREATE TABLE LIFE_EVENT(EVENT_ID int NOT NULL AUTO_INCREMENT,EVENT_NAME varchar(255) NOT NULL,PRODUCT_ID int NOT NULL, PRIMARY KEY(EVENT_ID),FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID));

